### ISSUE TITLE
Please add the NidoranMale and NidoranFemale to the inbuilt pokesniper.

### ISSUE THREAD

**Issue by lipun12ka4** [Logxn/PokemonGo-Bot#4250]
When I am clicking on the sniper link to snipe a NidoranMale an Error Message pops up.
Here is the screen shot.
I believe, it is due to the fact that the Pokemon NidoranMale has not been added to the sniping list somewhere.
Could you please look into this issue.
![errornidoranmale](https://cloud.githubusercontent.com/assets/4893328/22858990/1629d6c6-f0f4-11e6-8898-d16dbc91cbe0.PNG)

Thank you for such a wonderful script.

**Comment by Xelwon** [comment]
fixed.
