### ISSUE TITLE
Buy API, no code

### ISSUE THREAD

**Issue by Reyman69** [Logxn/PokemonGo-Bot#4259]
hello,

i bought API, and i dont receive nothing on e-mail.
now i see and i put a wrong email...
order 56827
what can i do?

thanks

**Comment by Xelwon** [comment]
Create your account with same email here.

https://eu.buddyauth.com/Account/Register

Confirm received link to activate your account.

Wait until 24 hours to receive your key to your email.

https://talk.pogodev.org/d/55-api-hashing-service-f-a-q

**Comment by Reyman69** [comment]
But i put the wrong mail. I cant validate/activate him and login with her.
My email is jorgemsv89@hotmail.com. 
I put jorgemv89@hotmail.com ...

**Comment by Ar1i** [comment]
I censored your email, its not our Service. You need to contact buddyauth.

Best regards
