### ISSUE TITLE
I paid $3.5 euro and get PokeHash Key, but still can't play

### ISSUE THREAD

**Issue by Bill56789** [Logxn/PokemonGo-Bot#4261]
######################## RULES. READ BEFORE POSTING! ########################

-> DONT OPEN A NEW ISSUE IF YOU DIDNT SEARCH YOUR PROBLEM IN THE ISSUES!

-> DONT OPEN A NEW ISSUE IF YOUR ISSUE GOT ANSWERED PERVIOUSLY!

-> DONT OPEN A NEW ISSUE IF YOUR "ISSUE" IS A QUESTION/SUGGESTION!

-> DONT OPEN A NEW ISSUE IF YOU DONT USE THE NEWEST VERSION!

If you do not respect them, your issue gets closed without any comment

#########################################################################

Describe your problem!:
When I press " start Bot " button, screen show program has problem and must shot down!!!
Can you tell me how to solved this? Thx. 

Add a screenshot!
![image](https://cloud.githubusercontent.com/assets/25867541/23094758/ba192e68-f639-11e6-8d83-a88646603a63.png)

**Comment by suljo94** [comment]
instal .net framework and start a fresh copy of the bot delete all the files and folders exept the .exe file

**Comment by Logxn** [comment]
^ this

**Comment by Bill56789** [comment]
Still can not, after start, screen shows nothing. 
Re-start show the same screen shot.

**Comment by Bill56789** [comment]
![image](https://cloud.githubusercontent.com/assets/25867541/23100068/a2010e0e-f6b1-11e6-91d8-1a9c39416050.png)
