### ISSUE TITLE
" IGNORE THIS : SENDING EXCEPTION INFORMATION TO LOG FILE " HELP ME 

### ISSUE THREAD

**Issue by samouelo199791** [Logxn/PokemonGo-Bot#4262]
Hello,

I just bought the hask key to run the pokemon go bot. I type all my information CORRECTLY and after that when i'm running the bot i see a message like this --> 

"  IGNORE THIS : SENDING EXCEPTION INFORMATION TO LOG FILE  "

Someone can explain me this, thanks.

![poke problem](https://cloud.githubusercontent.com/assets/25873227/23098141/1c531820-f647-11e6-88c0-046bd88972f2.png)

**Comment by Logxn** [comment]
Fixed, update
