### ISSUE TITLE
Key attached to the email

### ISSUE THREAD

**Issue by s1ckayeah** [Logxn/PokemonGo-Bot#4266]
Well, i've just bought an Ar1i's Pokebot 150 RPM. The main problem is, that i didn't know, that the key is attached to the email on which i have bought it. 

Is there any possibility to deactivate this key on current email and attach it to the other?

Thanks for helping.

**Comment by s1ckayeah** [comment]
Key has been reattached. But it's probably not recognized by the bot (mail and password is 100% correct, key too). Any ideas?

**Comment by Logxn** [comment]
What do you mean by its probably not recognized?

**Comment by s1ckayeah** [comment]
It's giving me the info that's hash, login or password is incorrect. I know that it seems like a noobish question, but i'm sure that hash (copy-pasted) is correct. Same with the login and pass (it works on my phone).
I've tried to redownload the bot, placed on different

**Comment by s1ckayeah** [comment]
Placed on different location - same error. Dunno what to do.

**Comment by s1ckayeah** [comment]
Did nothing, started working.
