### ISSUE TITLE
Missed ''Pokemon'' while using ItemPokeBall

### ISSUE THREAD

**Issue by jamiejvmasta** [Logxn/PokemonGo-Bot#4269]
The bot is missing many pokeballs when it's throwing to pokemon. Is this normal?

Add a screenshot!

![pokebot](https://cloud.githubusercontent.com/assets/25989895/23277879/d0ae0552-fa0f-11e6-84e0-2c3c29037314.png)

**Comment by Logxn** [comment]
yes this is normal
