### ISSUE TITLE
no pokesstop

### ISSUE THREAD

**Issue by Reyman69** [Logxn/PokemonGo-Bot#4270]
hello,

at moment i dont have more pokeballs.
i put to skip all pokemon and just farm pokestops to get more pokeballs...
he dont farm pokestops and i dont know why...
whats happening?

thanks
![no farm](https://cloud.githubusercontent.com/assets/21362941/23407407/b503ce0e-fdbb-11e6-9501-3e0d4b0a47b3.jpg)

**Comment by Logxn** [comment]
soft banned
