### ISSUE TITLE
UDS:DangerousObject.Multi.Generic

### ISSUE THREAD

**Issue by Bill56789** [Logxn/PokemonGo-Bot#4271]
Describe your problem!
After running a while, my anti-virus said find: UDS:DangerousObject.Multi.Generic and ask to remove.
Can anyone explain why before don't have this message but start from 3/1 new build? Thx.

**Comment by Logxn** [comment]
Its a false positive.
We dont know why at the moment, but other providers face the same problems.
Run it trough a virustotal scan and you'll see the only one who is complaining should be kaspersky.

We do warn you to not download from untrusted sources!!

**Comment by Bill56789** [comment]
got it, thx.



2017-03-04 4:09 GMT+08:00 Logan <notifications@github.com>:
