### ISSUE TITLE
how do i dowlad the program? i see the exe file but where do i get the rest of the fies so the .exe file will work? im totally lost

### ISSUE THREAD

**Issue by tamoknhba** [Logxn/PokemonGo-Bot#4279]
######################## RULES. READ BEFORE POSTING! ########################

-> DONT OPEN A NEW ISSUE IF YOU DIDNT SEARCH YOUR PROBLEM IN THE ISSUES!

-> DONT OPEN A NEW ISSUE IF YOUR ISSUE GOT ANSWERED PERVIOUSLY!

-> DONT OPEN A NEW ISSUE IF YOUR "ISSUE" IS A QUESTION/SUGGESTION!

-> DONT OPEN A NEW ISSUE IF YOU DONT USE THE NEWEST VERSION!

If you do not respect them, your issue gets closed without any comment

#########################################################################

Describe your problem!

Add a screenshot!

Choose a good title!

Dont forget to delete this template!

Post.

**Comment by tamoknhba** [comment]
ese help.i ied to useths ot wen it irst strtdyu hd all the filestother in the uil me.ow its jueefile. where is the rest of te files and how do i download them? please help!

**Comment by Logxn** [comment]
a) Dont formulate your whole question in the title - thats way to confusing
b) You will only need the .exe file. 
c) You can get rid of the rest of the files
