### ISSUE TITLE
All pokemon escape

### ISSUE THREAD

**Issue by jiji3731** [Logxn/PokemonGo-Bot#4281]
Hello,
Why all the pokemon run away but the pokestop work.
This happens very regiriously!
Is this a ban software?
If so, how to remove it if possible?
Thank you for your answers :)

**Comment by jiji3731** [comment]
A reply please :)
thank you :)

**Comment by Logxn** [comment]
Most likely you were jumping locations or your speed is set to high.
sorry we rarely check the github issues, only the discord issues thread
