### ISSUE TITLE
I just buy 3 month key but not works

### ISSUE THREAD

**Issue by Bill56789** [Logxn/PokemonGo-Bot#4282]
Describe your problem!
I just bought 3 months key but show API Key is incorrect or expired, pls help.
Add a screenshot!

Choose a good title!

Dont forget to delete this template!

Post.

**Comment by Logxn** [comment]
Thats strange. 
Maybe you were in the window where the bossland servers were down.

Please try again!

**Comment by Bill56789** [comment]
I think I found the reason, I bought Pokefarmer Key, this is not the same,
right?

2017-03-25 17:37 GMT+08:00 Logan <notifications@github.com>:

**Comment by Logxn** [comment]
No :/
