### ISSUE TITLE
There is a pending pokemon. Try latter

### ISSUE THREAD

**Issue by Bence98007** [Logxn/PokemonGo-Bot#4283]
Hi there!

When I try to snipe a pokemon, sometimes it fails (=> does.nothing) and it gives no message or consol.writeline. After this happens, I try to snipe an other pokemon but the bot sends me this messagebox:
There is a pending pokemon. Try latter
And no pokemon are captured by snipe.
I tried to fix this in the code, but couldn't find what cause this error. Maybe you guys do ;)

(I was following this project, when Ar1i started it. I made a lot of bug report, to help, so please take this a bit seriously :D And keep up the good work! :) )

**Comment by Xelwon** [comment]
Sorry. We need more information abut that problem " it fails" is not enough data.
Can you do a clean test doing the next steps?
1- delete or rename your config/log.txt file
2- run bot
3- enable verbose loggin option
4- make a snipe 
5- if it fails then send us the log.txt result
if not, repeat the snipe until get the fail.

**Comment by Logxn** [comment]
no response. closed
