### ISSUE TITLE
"Unbehandelte Außname" nach einigen Stunden

### ISSUE THREAD

**Issue by Experte9** [Logxn/PokemonGo-Bot#4284]
Nach einigen Stunden kommt ein Fehler 

![unbenannt](https://cloud.githubusercontent.com/assets/20842528/24631621/4d68ef9c-18c1-11e7-9494-a10bfb462e36.PNG)

Log: (siehe ganz unten)
[log.txt](https://github.com/Logxn/PokemonGo-Bot/files/891408/log.txt)

Hilfe xD
Danke

**Comment by Experte9** [comment]
After a vew hours there is an error

Log: (see the last entry)

Help xD
Thx

**Comment by Logxn** [comment]
Schau mal obs besser ist. 
Neue API bugt noch
