### ISSUE TITLE
API buggt noch immer sehr stark

### ISSUE THREAD

**Issue by Experte9** [Logxn/PokemonGo-Bot#4287]
![unbenannt](https://cloud.githubusercontent.com/assets/20842528/24776247/45c904f0-1b20-11e7-904f-ff5659de6e77.PNG)

[log.txt](https://github.com/Logxn/PokemonGo-Bot/files/904000/log.txt)

Hier auch schon ähnliches Problem gehabt:
#4284

Schaut mal nach was ihr machen könnt
(vielleicht nicht gleich schließen, würde ich auch selbt machen wenn es dann läuft)

Danke ;)

**Comment by Logxn** [comment]
fixed
