### ISSUE TITLE
API Version zu neu?

### ISSUE THREAD

**Issue by Experte9** [Logxn/PokemonGo-Bot#4288]
Mir wird Angezeigt das meine API Version zu neu ist, habe aber nichts geändert
![unbenannt2](https://cloud.githubusercontent.com/assets/20842528/24841162/8d0a5bc0-1d7d-11e7-8211-c4b2a09d15e1.PNG)

Was kann ich jetzt machen?

**Comment by Logxn** [comment]
Lad mal neuste exe runter. haben wohl vergessen die version zu pushen

**Comment by Experte9** [comment]
Ja wahrscheinlich, und autoupdate hat auch nicht geklappt.
 und ist es normal das der bot jetzt die ganze Zeit  Altitude aufzeigt?
![3](https://cloud.githubusercontent.com/assets/20842528/24872218/efb4fe7a-1e1c-11e7-9216-43a6014d2ef4.PNG)
