### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by Bill56789** [Logxn/PokemonGo-Bot#4289]
Describe your problem!

No function after couple minutes, start from 4/9 build, and no pic of pokemons. 
Add a screenshot!

![image](https://cloud.githubusercontent.com/assets/25867541/24906110/0f2b82d4-1ee9-11e7-9b7b-94d50d7eb1b8.png)
![image](https://cloud.githubusercontent.com/assets/25867541/24906129/1e892b28-1ee9-11e7-9785-6ac31a5b6d3c.png)

**Comment by BigManTyrone** [comment]
rip lv 37 account nice name

**Comment by Bill56789** [comment]
What's that mean? I'd ban?

2017-04-12 15:31 GMT+08:00 BigManTyrone <notifications@github.com>:

**Comment by Bill56789** [comment]
I use new build today, at first snipers function is ok, but after a while when use snipers, always no pokemon found, continue like that, than no more farm & catch pokemon. Its never happen, pls help, thx.

**Comment by Bill56789** [comment]
![image](https://cloud.githubusercontent.com/assets/25867541/24956428/2a190252-1fba-11e7-82e3-6de32e278704.png)

**Comment by Bill56789** [comment]
Screen show " Invalid Token ", than no more farm & catch pokemon, what's that mean?

**Comment by Bill56789** [comment]
Today's build, snipers still can't find pokemon, than no more farm & catch function.

**Comment by Bill56789** [comment]
new build v 1.3.4.2 no function at all, screen stop here: 

![2017-04-16_190744](https://cloud.githubusercontent.com/assets/25867541/25070693/431742b6-22d8-11e7-852d-f730c4566db4.jpg)

**Comment by Xelwon** [comment]
sorry, try latest version.
You have to delete all files, use latest .exe and reput all your configuration.
Most sure you have enabled "start paused option", if this option is enabled you have to press the resume walk button in map tab, to the bot starts to walk.
