### ISSUE TITLE
Repeat Route is not working

### ISSUE THREAD

**Issue by Experte9** [Logxn/PokemonGo-Bot#4291]
Title...
![unbenannt3](https://cloud.githubusercontent.com/assets/20842528/25236780/0186afe4-25e9-11e7-9f19-0930bfc8d62c.PNG)
und ja, ich habe vorher eine Route definiert.

**Comment by Xelwon** [comment]
please use latest version. And check it again.
Repeat route works only with the defined points in the map.
For example you press define route, mark 3 pokestos, enable repeat route,
then bot will go to the 3 marked points and go bac for the same 3 points before of continue normal walking.
