### ISSUE TITLE
"Atention, current API version is new and still not supported by Bot"

### ISSUE THREAD

**Issue by Takotero** [Logxn/PokemonGo-Bot#4328]
Hey there, 
I'm having big problems with the bot. Exactly with this:
![screenshot_3](https://user-images.githubusercontent.com/21259916/40578633-a7a5765c-6117-11e8-8147-bad53b9b0b76.png)

I know that someone posted an issue like this, but I wasn't able to solve it.

**Comment by Logxn** [comment]
read manual
